---------------------------------------------------------------
-------------------------- CRM SNAPSHOTS  ---------------------
---------------------------------------------------------------

alter session set QUOTED_IDENTIFIERS_IGNORE_CASE = false;

use database &{dbname};
use warehouse &{whname};
use schema &{schemaname};
use role &{rolename};

-- router -------------------------------------

MERGE INTO &{dbname}.&{schemaname}.PORTAL_ROUTER_SNAPSHOT as target USING
(
select  $1:_id:"$oid"::string as portal_router_id,
            $1:adding_client::string as adding_client,
            $1:adding_device_id::string as adding_device_id,
            $1:business_id:"$oid"::string as business_id,
            $1:created:"$date"::datetime as created,
            $1:current_routertype_id::string as current_routertype_id,
            $1:current_version_id:"$oid"::string as current_version_id,
            $1:date_added:"$date"::datetime as date_added,
            $1:desired_version_id:"$oid"::string as desired_version_id,
            $1:dns_type::string as dns_type,
            $1:downlink_speed::string as downlink_speed,
            $1:gateway_id::string as gateway_id,
            $1:installed:"$date"::datetime as installed,
            $1:internal_ipaddress::string as internal_ipaddress,
            $1:ipaddress::string as ipaddress,
            $1:key_1::string as key_1,
            $1:key_2::string as key_2,
            $1:lan_mac::string as lan_mac,
            $1:last_crm_req:"$date"::datetime as last_crm_req,
            $1:last_ping:"$date"::datetime as last_ping,
            $1:last_probe_upload:"$date"::datetime as last_probe_upload,
            $1:last_sys_load:"$date"::datetime as last_sys_load,
            $1:last_sys_memfree:"$date"::datetime as last_sys_memfree,
            $1:last_sys_uptime:"$date"::datetime as last_sys_uptime,
            $1:last_update:"$date"::datetime as last_update,
            $1:last_update_check:"$date"::datetime as last_update_check,
            case when $1:last_wifidog_uptime:"$numberLong" is not null then null else $1:last_wifidog_uptime::integer end as last_wifidog_uptime,
            $1:latitude::float as latitude,
            $1:longitude::float as longitude,
            $1:management_port::number(38,0) as management_port,
            $1:original_password::string as original_password,
            $1:original_username::string as original_username,
            $1:password::string as password,
            $1:pinged_recently::boolean as pinged_recently,
            $1:security_1::string as security_1,
            $1:security_2::string as security_2,
            $1:security_3::string as security_3,
            $1:security_4::string as security_4,
            $1:ssh_portnum::number(38,0) as ssh_portnum,
            $1:ssh_tunnel_available::boolean as ssh_tunnel_available,
            $1:ssid_1::string as ssid_1,
            $1:ssid_2::string as ssid_2,
            $1:ssid_3::string as ssid_3,
            $1:ssid_4::string as ssid_4,
            $1:stock_firmware_version_id::string as stock_firmware_version_id,
            $1:stock_routertype_id::string as stock_routertype_id,
            $1:street_address::string as street_address,
            $1:time_zone::string as time_zone,
            $1:update_available:"$date"::datetime as update_available,
            $1:updated:"$date"::datetime as updated,
            $1:uplink_speed::number(38,0) as uplink_speed,
            $1:username::string as username,
            $1:userprofile_id:"$oid"::string as userprofile_id,
            $1:wan_connection_type::string as wan_connection_type,
            $1:wan_dns::string as wan_dns,
            $1:wan_gateway::string as wan_gateway,
            $1:wan_ip::string as wan_ip,
            $1:wan_mac::string as wan_mac,
            $1:wan_subnet_mask::string as wan_subnet_mask,
            $1:wifidog_profile::string as wifidog_profile,
            $1:wlan_mac::string as wlan_mac,
      	    '&{asof_date}'::date as asof_date
FROM @&{stageurl}/portal_router.json (file_format => 's3_mongo_json_format')
) as source ON target.asof_date = source.asof_date and target.business_id = source.business_id
WHEN not matched then insert
(PORTAL_ROUTER_ID,
ADDING_CLIENT,
ADDING_DEVICE_ID,
BUSINESS_ID,
CREATED,
CURRENT_ROUTERTYPE_ID,
CURRENT_VERSION_ID,
DATE_ADDED,
DESIRED_VERSION_ID,
DNS_TYPE,
DOWNLINK_SPEED,
GATEWAY_ID,
INSTALLED,
INTERNAL_IPADDRESS,
IPADDRESS,
KEY_1,
KEY_2,
LAN_MAC,
LAST_CRM_REQ,
LAST_PING,
LAST_PROBE_UPLOAD,
LAST_SYS_LOAD,
LAST_SYS_MEMFREE,
LAST_SYS_UPTIME,
LAST_UPDATE,
LAST_UPDATE_CHECK,
LAST_WIFIDOG_UPTIME,
LATITUDE,
LONGITUDE,
MANAGEMENT_PORT,
ORIGINAL_PASSWORD,
ORIGINAL_USERNAME,
PASSWORD,
PINGED_RECENTLY,
SECURITY_1,
SECURITY_2,
SECURITY_3,
SECURITY_4,
SSH_PORTNUM,
SSH_TUNNEL_AVAILABLE,
SSID_1,
SSID_2,
SSID_3,
SSID_4,
STOCK_FIRMWARE_VERSION_ID,
STOCK_ROUTERTYPE_ID,
STREET_ADDRESS,
TIME_ZONE,
UPDATE_AVAILABLE,
UPDATED,
UPLINK_SPEED,
USERNAME,
USERPROFILE_ID,
WAN_CONNECTION_TYPE,
WAN_DNS,
WAN_GATEWAY,
WAN_IP,
WAN_MAC,
WAN_SUBNET_MASK,
WIFIDOG_PROFILE,
WLAN_MAC,
ASOF_DATE)
VALUES (source.PORTAL_ROUTER_ID,
source.ADDING_CLIENT,
source.ADDING_DEVICE_ID,
source.BUSINESS_ID,
source.CREATED,
source.CURRENT_ROUTERTYPE_ID,
source.CURRENT_VERSION_ID,
source.DATE_ADDED,
source.DESIRED_VERSION_ID,
source.DNS_TYPE,
source.DOWNLINK_SPEED,
source.GATEWAY_ID,
source.INSTALLED,
source.INTERNAL_IPADDRESS,
source.IPADDRESS,
source.KEY_1,
source.KEY_2,
source.LAN_MAC,
source.LAST_CRM_REQ,
source.LAST_PING,
source.LAST_PROBE_UPLOAD,
source.LAST_SYS_LOAD,
source.LAST_SYS_MEMFREE,
source.LAST_SYS_UPTIME,
source.LAST_UPDATE,
source.LAST_UPDATE_CHECK,
source.LAST_WIFIDOG_UPTIME,
source.LATITUDE,
source.LONGITUDE,
source.MANAGEMENT_PORT,
source.ORIGINAL_PASSWORD,
source.ORIGINAL_USERNAME,
source.PASSWORD,
source.PINGED_RECENTLY,
source.SECURITY_1,
source.SECURITY_2,
source.SECURITY_3,
source.SECURITY_4,
source.SSH_PORTNUM,
source.SSH_TUNNEL_AVAILABLE,
source.SSID_1,
source.SSID_2,
source.SSID_3,
source.SSID_4,
source.STOCK_FIRMWARE_VERSION_ID,
source.STOCK_ROUTERTYPE_ID,
source.STREET_ADDRESS,
source.TIME_ZONE,
source.UPDATE_AVAILABLE,
source.UPDATED,
source.UPLINK_SPEED,
source.USERNAME,
source.USERPROFILE_ID,
source.WAN_CONNECTION_TYPE,
source.WAN_DNS,
source.WAN_GATEWAY,
source.WAN_IP,
source.WAN_MAC,
source.WAN_SUBNET_MASK,
source.WIFIDOG_PROFILE,
source.WLAN_MAC,
source.ASOF_DATE)
;
