CREATE OR REPLACE VIEW ZENALYTICS.ADS.PEETS_ENRICHED_SIGHTINGS_VW 
COMMENT='Finished enriched sightings for Peets businesses' as
SELECT
    ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.business_id as location_id,
    ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.client_mac,
    TO_TIMESTAMP(ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.start_time / 1000) as start_time,
    TO_TIMESTAMP(ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.end_time / 1000) as end_time,
    to_date(TO_TIMESTAMP(ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.end_time / 1000)) as date,
    ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.is_walk_in,
    ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.contact_info
FROM ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS 
INNER JOIN ZENALYTICS.ADS.PEETS_LOCATIONS
ON ZENALYTICS.ADS.PEETS_LOCATIONS.location_id = ZENALYTICS.PRESENCE.ENRICHED_SIGHTINGS.business_id
WHERE contact_info IS NOT NULL AND status = 'FINISHED'

