SELECT REPORT_DATE,
       PRODUCT,
       ACCOUNT_ID,
       count(DISTINCT CASE WHEN ACTIVE_SUBSCRIPTION_FL THEN SUBSCRIPTION_ID END)             AS ACTIVE_SUBSCRIPTIONS,
       sum(LICENSE_QUANTITY)                                                                 AS ACTIVE_LICENSES,
       SUM(CASE
               WHEN ACTIVE_SUBSCRIPTION_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE
               ELSE 0 END)                                                                   AS ACTIVE_SUBSCRIPTION_MRR,

       count(DISTINCT CASE WHEN NEW_REALIZED_FL AND NOT MNIR_FL THEN SUBSCRIPTION_ID END)    AS NEW_SUBSCRIPTIONS,
       SUM(CASE WHEN NEW_REALIZED_FL AND NOT MNIR_FL THEN LICENSE_QUANTITY ELSE 0 END)       AS NEW_LICENSES,
       SUM(CASE
               WHEN NEW_REALIZED_FL AND NOT MNIR_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE
               ELSE 0 END)                                                                   AS NEW_SUBSCRIPTION_MRR,

       count(DISTINCT CASE WHEN MNIR_FL THEN SUBSCRIPTION_ID ELSE NULL END)                  AS MNIR_SUBSCRIPTIONS, -- added reactivation fl 11/7
       SUM(CASE WHEN MNIR_FL THEN LICENSE_QUANTITY ELSE 0 END)                               AS MNIR_LICENSES,      -- added reactivation fl 11/7
       SUM(CASE WHEN MNIR_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END)               AS MNIR_SUBSCRIPTION_MRR,

       count(DISTINCT CASE WHEN SUBSCRIPTION_EXPANSION_FL THEN SUBSCRIPTION_ID END)          AS SUBSCRIPTION_EXPANSION,
       SUM(CASE
               WHEN SUBSCRIPTION_EXPANSION_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE
               ELSE 0 END)                                                                   AS SUBSCRIPTION_EXPANSION_MRR,

       count(DISTINCT CASE WHEN UPGRADE_FL THEN SUBSCRIPTION_ID END)                         AS SUBSCRIPTION_UPGRADES,
       SUM(
               CASE WHEN UPGRADE_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END)        AS SUBSCRIPTION_UPGRADES_MRR,

       count(DISTINCT CASE WHEN DOWNGRADE_FL THEN SUBSCRIPTION_ID END)                       AS SUBSCRIPTION_DOWNGRADES,
       SUM(
               CASE WHEN DOWNGRADE_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END)      AS SUBSCRIPTION_DOWNGRADES_MRR,

       count(DISTINCT CASE WHEN CHURN_FL THEN SUBSCRIPTION_ID END)                           AS CHURN,
       SUM(CASE WHEN CHURN_FL THEN LICENSE_QUANTITY ELSE 0 END)                              AS CHURN_LICENSES,
       SUM(CASE WHEN CHURN_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END)              AS CHURN_MRR,

       SUM(CASE
               WHEN ACTIVE_SUBSCRIPTION_FL THEN LICENSE_EXPANSION_CONTRACTION
               ELSE 0 END)                                                                   AS LICENSE_EXPANSION_CONTRACTION,
       SUM(
               CASE WHEN ACTIVE_SUBSCRIPTION_FL THEN MRR_EXPANSION_CONTRACTION ELSE 0 END)   AS MRR_EXPANSION_CONTRACTION,

       count(DISTINCT CASE WHEN DELINQUENCY_CHURN_FL THEN SUBSCRIPTION_ID END)               AS DELINQUENCY_CHURNS,
       SUM(CASE WHEN DELINQUENCY_CHURN_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END)  AS DELINQUENCY_CHURN_MRR,

       count(DISTINCT CASE WHEN SUBSCRIPTION_CHURN_FL THEN SUBSCRIPTION_ID END)              AS SUBSCRIPTION_CHURNS,
       SUM(CASE WHEN SUBSCRIPTION_CHURN_FL THEN MONTHLY_SUBSCRIPTION_SERVICE_FEE ELSE 0 END) AS SUBSCRIPTION_CHURN_MRR,
       current_date                                                                          AS ASOF_DATE
FROM {{ ref('mart_bizint__subscription_details_fact') }} F
GROUP BY ROLLUP (1, 2, 3)
