SELECT SUBSTR(OPPORTUNITY.ID, 1, 15) AS    OPPORTUNITY_ID,
       CASE
           WHEN OPPORTUNITYLINEITEM.PRODUCTCODE = 'Ads' THEN 'Ads'
           WHEN OPPORTUNITYLINEITEM.PRODUCTCODE IN ('Classic', 'Acquire', 'Retain', 'Build') THEN 'Core'
           ELSE OPPORTUNITYLINEITEM.PRODUCTCODE
           END                            AS    PRODUCT_CATEGORY,
       OPPORTUNITY.STAGENAME,
       SUM(OPPORTUNITYLINEITEM.QUANTITY)   OLI_QUANTITY,
       SUM(OPPORTUNITYLINEITEM.UNITPRICE)  OLI_UNITPRICE,
       SUM(OPPORTUNITYLINEITEM.SUBTOTAL)   OLI_SUBTOTAL,
       SUM(OPPORTUNITYLINEITEM.TOTALPRICE) OLI_TOTALPRICE,
       current_date                       AS    ASOF_DATE
FROM {{ ref('stg_sfdc__opportunity') }} AS OPPORTUNITY
         LEFT JOIN {{ ref('stg_sfdc__opportunitylineitem') }} AS OPPORTUNITYLINEITEM ON OPPORTUNITYLINEITEM.OPPORTUNITYID = OPPORTUNITY.ID
WHERE ((OPPORTUNITY.ISCLOSED = TRUE AND OPPORTUNITY.ISWON = TRUE) OR OPPORTUNITY.STAGENAME = 'Stage 4: Decision')
GROUP BY OPPORTUNITY_ID, PRODUCT_CATEGORY, STAGENAME