SELECT  $1                  AS id
       ,$2                  AS salesforce_quote_id
       ,$3                  AS billing_city
       ,$4                  AS billing_country
       ,$5                  AS billing_state
       ,$6                  AS billing_street
       ,$7                  AS billing_postal_code
       ,$8                  AS billing_method
       ,$9                  AS contact_id
       ,$10                 AS contact_email
       ,$11                 AS contact_name
       ,$12                 AS pricebook2_id
       ,$13                 AS oppurtunity_id
       ,$14::boolean        AS auto_sign
       ,$15                 AS status
       ,$16                 AS social_media_accounts
       ,$17::timestamp      AS created
       ,$18::timestamp      AS updated
       ,$19                 AS type
       ,$20                 AS billing_name
       ,$21                 AS quote_to_city
       ,$22                 AS quote_to_country
       ,$23                 AS quote_to_state
       ,$24                 AS quote_to_street
       ,$25                 AS quote_to_postal_code
       ,$26                 AS description
       ,$27                 AS quote_to_name
       ,current_timestamp() AS asof_date
FROM {{ most_recent_s3_file_name('AMS_ACCOUNTS', 'AMS_ACCOUNTS_S3_STAGE', '.*/salesforce_quote.csv') }}
