---------------------------------------------------------------
-------------------------- CRM SNAPSHOTS  ---------------------
---------------------------------------------------------------

alter session set QUOTED_IDENTIFIERS_IGNORE_CASE = false;

use database &{dbname};
use warehouse &{whname};
use schema &{schemaname};
use role &{rolename};

-- load crm snapshots

MERGE INTO &{dbname}.&{schemaname}.PORTAL_BUSINESSPROFILE_SNAPSHOT as target USING
(
select  $1:_id:"$oid"::string as business_id,
      $1:address::variant as address, 
      $1:announcements::string as announcements, 
      $1:authorizations[0]::string as authorizations,
      $1:authorizations_optional::boolean as authorizations_optional,
      $1:contact_firstname::string as contact_firstname,
      $1:contact_lastname::string as contact_lastname,
      $1:contact_phone::string as contact_phone,
      $1:created:"$date"::datetime as created_date,
      $1:customer_tags::variant as customer_tags,
      $1:facebook_access_token::string as facebook_access_token,
      $1:facebook_like_url::string as facebook_like_url,
      $1:feature_override::string as feature_override,
      $1:feedback_contact_id:"$oid"::string as feedback_contact_id,
      $1:foursquare_url::string as foursquare_url,
      $1:google_autopopulate_self_attempted::boolean as google_autopopulate_self_attempted,
      $1:googleplus_url::string as googleplus_url,
      $1:hide_welcome_email::boolean as hide_welcome_email,
      $1:hours::variant as hours,
      $1:inactive::boolean as inactive,
      $1:instagram_screen_name::string as instagram_screen_name,
      $1:installed:"$date"::datetime as installed_date,
      $1:is_whitelabel::boolean as is_whitelabel,
      $1:last_crm_req:"$date"::datetime as last_crm_req,
      $1:last_probe_upload:"$date"::datetime as last_probe_upload,
      $1:locale::string as locale,
      $1:logo_mime::string as logo_mime,
      $1:logo_original::string as logo_original,
      $1:logo_standard::string as logo_standard,
      $1:mist_api_secret::string as mist_api_secret,
      $1:name::string as name,
      $1:network_lead_submitted::boolean as network_lead_submitted,
      $1:notifications_enabled::boolean as notifications_enabled,
      $1:onboarded::boolean as onboarded,
      $1:opentable_id::string as opentable_id,
      $1:opentable_url::string as opentable_url,
      $1:parent_id:"$oid"::string as parent_id,
      $1:phone::string as phone,
      $1:pilot_business::boolean as pilot_business,
      $1:pinterest_screen_name::string as pinterest_screen_name,
      $1:privacy_policy::string as privacy_policy,
      $1:private_key::string as private_key,
      $1:private_ssid::string as private_ssid,
      $1:public_ssid::string as public_ssid,
      $1:ruckus_password::string as ruckus_password,
      $1:ruckus_venue_id::string as ruckus_venue_id,
      $1:ruckus_venue_psk::string as ruckus_venue_psk,
      $1:salesforce_id::string as salesforce_id,
      $1:shortname::string as shortname,
      $1:terms_of_service::string as terms_of_service,
      $1:test_business::boolean as test_business,
      case when $1:ticket_revenue_avg:"$numberLong" is not null then null else $1:ticket_revenue_avg::float end as ticket_revenue_avg, 
      $1:time_zone::string as time_zone,
      $1:tripadvisor_url::string as tripadvisor_url,
      $1:twitter_screen_name::string as twitter_screen_name,
      $1:updated:"$date"::datetime as updated,
      $1:userdata_optional::boolean as userdata_optional,
      $1:webform_trigger_enabled::boolean as  webform_trigger_enabled,    
      $1:website_url::string as website_url,
      $1:yelp_url::string as yelp_url,
      $1:youtube_url::string as youtube_url,
      '&{asof_date}'::date as asof_date
FROM @&{stagename}/&{stagepath}/portal_businessprofile.json (file_format => 's3_mongo_json_format')
) as source ON target.asof_date = source.asof_date
WHEN not matched then insert 
(BUSINESS_ID,
ADDRESS,
ANNOUNCEMENTS,
AUTHORIZATIONS,
AUTHORIZATIONS_OPTIONAL,
CONTACT_FIRSTNAME,
CONTACT_LASTNAME,
CONTACT_PHONE,
CREATED_DATE,
CUSTOMER_TAGS,
FACEBOOK_ACCESS_TOKEN,
FACEBOOK_LIKE_URL,
FEATURE_OVERRIDE,
FEEDBACK_CONTACT_ID,
FOURSQUARE_URL,
GOOGLE_AUTOPOPULATE_SELF_ATTEMPTED,
GOOGLEPLUS_URL,
HIDE_WELCOME_EMAIL,
HOURS,
INACTIVE,
INSTAGRAM_SCREEN_NAME,
INSTALLED_DATE,
IS_WHITELABEL,
LAST_CRM_REQ,
LAST_PROBE_UPLOAD,
LOCALE,
LOGO_MIME,
LOGO_ORIGINAL,
LOGO_STANDARD,
MIST_API_SECRET,
NAME,
NETWORK_LEAD_SUBMITTED,
NOTIFICATIONS_ENABLED,
ONBOARDED,
OPENTABLE_ID,
OPENTABLE_URL,
PARENT_ID,
PHONE,
PILOT_BUSINESS,
PINTEREST_SCREEN_NAME,
PRIVACY_POLICY,
PRIVATE_KEY,
PRIVATE_SSID,
PUBLIC_SSID,
RUCKUS_PASSWORD,
RUCKUS_VENUE_ID,
RUCKUS_VENUE_PSK,
SALESFORCE_ID,
SHORTNAME,
TERMS_OF_SERVICE,
TEST_BUSINESS,
TICKET_REVENUE_AVG,
TIME_ZONE,
TRIPADVISOR_URL,
TWITTER_SCREEN_NAME,
UPDATED,
USERDATA_OPTIONAL,
WEBFORM_TRIGGER_ENABLED,
WEBSITE_URL,
YELP_URL,
YOUTUBE_URL,
ASOF_DATE)
VALUES (source.BUSINESS_ID,
source.ADDRESS,
source.ANNOUNCEMENTS,
source.AUTHORIZATIONS,
source.AUTHORIZATIONS_OPTIONAL,
source.CONTACT_FIRSTNAME,
source.CONTACT_LASTNAME,
source.CONTACT_PHONE,
source.CREATED_DATE,
source.CUSTOMER_TAGS,
source.FACEBOOK_ACCESS_TOKEN,
source.FACEBOOK_LIKE_URL,
source.FEATURE_OVERRIDE,
source.FEEDBACK_CONTACT_ID,
source.FOURSQUARE_URL,
source.GOOGLE_AUTOPOPULATE_SELF_ATTEMPTED,
source.GOOGLEPLUS_URL,
source.HIDE_WELCOME_EMAIL,
source.HOURS,
source.INACTIVE,
source.INSTAGRAM_SCREEN_NAME,
source.INSTALLED_DATE,
source.IS_WHITELABEL,
source.LAST_CRM_REQ,
source.LAST_PROBE_UPLOAD,
source.LOCALE,
source.LOGO_MIME,
source.LOGO_ORIGINAL,
source.LOGO_STANDARD,
source.MIST_API_SECRET,
source.NAME,
source.NETWORK_LEAD_SUBMITTED,
source.NOTIFICATIONS_ENABLED,
source.ONBOARDED,
source.OPENTABLE_ID,
source.OPENTABLE_URL,
source.PARENT_ID,
source.PHONE,
source.PILOT_BUSINESS,
source.PINTEREST_SCREEN_NAME,
source.PRIVACY_POLICY,
source.PRIVATE_KEY,
source.PRIVATE_SSID,
source.PUBLIC_SSID,
source.RUCKUS_PASSWORD,
source.RUCKUS_VENUE_ID,
source.RUCKUS_VENUE_PSK,
source.SALESFORCE_ID,
source.SHORTNAME,
source.TERMS_OF_SERVICE,
source.TEST_BUSINESS,
source.TICKET_REVENUE_AVG,
source.TIME_ZONE,
source.TRIPADVISOR_URL,
source.TWITTER_SCREEN_NAME,
source.UPDATED,
source.USERDATA_OPTIONAL,
source.WEBFORM_TRIGGER_ENABLED,
source.WEBSITE_URL,
source.YELP_URL,
source.YOUTUBE_URL,
source.ASOF_DATE)
;



-- router -------------------------------------

MERGE INTO &{dbname}.&{schemaname}.PORTAL_ROUTER_SNAPSHOT as target USING
(
select  $1:_id:"$oid"::string as portal_router_id,
            $1:adding_client::string as adding_client,
            $1:adding_device_id::string as adding_device_id,
            $1:business_id:"$oid"::string as business_id,
            $1:created:"$date"::datetime as created,
            $1:current_routertype_id::string as current_routertype_id,
            $1:current_version_id:"$oid"::string as current_version_id,
            $1:date_added:"$date"::datetime as date_added,
            $1:desired_version_id:"$oid"::string as desired_version_id,
            $1:dns_type::string as dns_type,
            $1:downlink_speed::string as downlink_speed,
            $1:gateway_id::string as gateway_id,
            $1:installed:"$date"::datetime as installed,
            $1:internal_ipaddress::string as internal_ipaddress,
            $1:ipaddress::string as ipaddress,
            $1:key_1::string as key_1,
            $1:key_2::string as key_2,
            $1:lan_mac::string as lan_mac,
            $1:last_crm_req:"$date"::datetime as last_crm_req,
            $1:last_ping:"$date"::datetime as last_ping,
            $1:last_probe_upload:"$date"::datetime as last_probe_upload,
            $1:last_sys_load:"$date"::datetime as last_sys_load,
            $1:last_sys_memfree:"$date"::datetime as last_sys_memfree,
            $1:last_sys_uptime:"$date"::datetime as last_sys_uptime,
            $1:last_update:"$date"::datetime as last_update,
            $1:last_update_check:"$date"::datetime as last_update_check,
            case when $1:last_wifidog_uptime:"$numberLong" is not null then null else $1:last_wifidog_uptime::integer end as last_wifidog_uptime,
            $1:latitude::float as latitude,
            $1:longitude::float as longitude,
            $1:management_port::number(38,0) as management_port,
            $1:original_password::string as original_password,
            $1:original_username::string as original_username,
            $1:password::string as password,
            $1:pinged_recently::boolean as pinged_recently,
            $1:security_1::string as security_1,
            $1:security_2::string as security_2,
            $1:security_3::string as security_3,
            $1:security_4::string as security_4,
            $1:ssh_portnum::number(38,0) as ssh_portnum,
            $1:ssh_tunnel_available::boolean as ssh_tunnel_available,
            $1:ssid_1::string as ssid_1,
            $1:ssid_2::string as ssid_2,
            $1:ssid_3::string as ssid_3,
            $1:ssid_4::string as ssid_4,
            $1:stock_firmware_version_id::string as stock_firmware_version_id,
            $1:stock_routertype_id::string as stock_routertype_id,
            $1:street_address::string as street_address,
            $1:time_zone::string as time_zone,
            $1:update_available:"$date"::datetime as update_available,
            $1:updated:"$date"::datetime as updated,
            $1:uplink_speed::number(38,0) as uplink_speed,
            $1:username::string as username,
            $1:userprofile_id:"$oid"::string as userprofile_id,
            $1:wan_connection_type::string as wan_connection_type,
            $1:wan_dns::string as wan_dns,
            $1:wan_gateway::string as wan_gateway,
            $1:wan_ip::string as wan_ip,
            $1:wan_mac::string as wan_mac,  
            $1:wan_subnet_mask::string as wan_subnet_mask,
            $1:wifidog_profile::string as wifidog_profile,
            $1:wlan_mac::string as wlan_mac,
      	    '&{asof_date}'::date as asof_date
FROM @&{stagename}/&{stagepath}/portal_router.json (file_format => 's3_mongo_json_format')
) as source ON target.asof_date = source.asof_date
WHEN not matched then insert 
(PORTAL_ROUTER_ID,
ADDING_CLIENT,
ADDING_DEVICE_ID,
BUSINESS_ID,
CREATED,
CURRENT_ROUTERTYPE_ID,
CURRENT_VERSION_ID,
DATE_ADDED,
DESIRED_VERSION_ID,
DNS_TYPE,
DOWNLINK_SPEED,
GATEWAY_ID,
INSTALLED,
INTERNAL_IPADDRESS,
IPADDRESS,
KEY_1,
KEY_2,
LAN_MAC,
LAST_CRM_REQ,
LAST_PING,
LAST_PROBE_UPLOAD,
LAST_SYS_LOAD,
LAST_SYS_MEMFREE,
LAST_SYS_UPTIME,
LAST_UPDATE,
LAST_UPDATE_CHECK,
LAST_WIFIDOG_UPTIME,
LATITUDE,
LONGITUDE,
MANAGEMENT_PORT,
ORIGINAL_PASSWORD,
ORIGINAL_USERNAME,
PASSWORD,
PINGED_RECENTLY,
SECURITY_1,
SECURITY_2,
SECURITY_3,
SECURITY_4,
SSH_PORTNUM,
SSH_TUNNEL_AVAILABLE,
SSID_1,
SSID_2,
SSID_3,
SSID_4,
STOCK_FIRMWARE_VERSION_ID,
STOCK_ROUTERTYPE_ID,
STREET_ADDRESS,
TIME_ZONE,
UPDATE_AVAILABLE,
UPDATED,
UPLINK_SPEED,
USERNAME,
USERPROFILE_ID,
WAN_CONNECTION_TYPE,
WAN_DNS,
WAN_GATEWAY,
WAN_IP,
WAN_MAC,
WAN_SUBNET_MASK,
WIFIDOG_PROFILE,
WLAN_MAC,
ASOF_DATE)
VALUES (source.PORTAL_ROUTER_ID,
source.ADDING_CLIENT,
source.ADDING_DEVICE_ID,
source.BUSINESS_ID,
source.CREATED,
source.CURRENT_ROUTERTYPE_ID,
source.CURRENT_VERSION_ID,
source.DATE_ADDED,
source.DESIRED_VERSION_ID,
source.DNS_TYPE,
source.DOWNLINK_SPEED,
source.GATEWAY_ID,
source.INSTALLED,
source.INTERNAL_IPADDRESS,
source.IPADDRESS,
source.KEY_1,
source.KEY_2,
source.LAN_MAC,
source.LAST_CRM_REQ,
source.LAST_PING,
source.LAST_PROBE_UPLOAD,
source.LAST_SYS_LOAD,
source.LAST_SYS_MEMFREE,
source.LAST_SYS_UPTIME,
source.LAST_UPDATE,
source.LAST_UPDATE_CHECK,
source.LAST_WIFIDOG_UPTIME,
source.LATITUDE,
source.LONGITUDE,
source.MANAGEMENT_PORT,
source.ORIGINAL_PASSWORD,
source.ORIGINAL_USERNAME,
source.PASSWORD,
source.PINGED_RECENTLY,
source.SECURITY_1,
source.SECURITY_2,
source.SECURITY_3,
source.SECURITY_4,
source.SSH_PORTNUM,
source.SSH_TUNNEL_AVAILABLE,
source.SSID_1,
source.SSID_2,
source.SSID_3,
source.SSID_4,
source.STOCK_FIRMWARE_VERSION_ID,
source.STOCK_ROUTERTYPE_ID,
source.STREET_ADDRESS,
source.TIME_ZONE,
source.UPDATE_AVAILABLE,
source.UPDATED,
source.UPLINK_SPEED,
source.USERNAME,
source.USERPROFILE_ID,
source.WAN_CONNECTION_TYPE,
source.WAN_DNS,
source.WAN_GATEWAY,
source.WAN_IP,
source.WAN_MAC,
source.WAN_SUBNET_MASK,
source.WIFIDOG_PROFILE,
source.WLAN_MAC,
source.ASOF_DATE)
;
