SELECT  GET_PATH($1,'_id:$oid')::string                                                                                                                     AS business_id
       ,$1:address::variant                                                                                                                         AS address
       ,$1:announcements::string                                                                                                                    AS announcements
       ,$1:authorizations[0]::string                                                                                                                AS authorizations
       ,$1:authorizations_optional::boolean                                                                                                         AS authorizations_optional
       ,$1:contact_firstname::string                                                                                                                AS contact_firstname
       ,$1:contact_lastname::string                                                                                                                 AS contact_lastname
       ,$1:contact_phone::string                                                                                                                            AS contact_phone
       ,GET_PATH($1,'created:$date')::datetime                                                                                                      AS created_date
       ,$1:customer_tags::variant                                                                                                                   AS customer_tags
       ,$1:facebook_access_token::string                                                                                                            AS facebook_access_token
       ,$1:facebook_like_url::string                                                                                                                AS facebook_like_url
       ,$1:feature_override::string                                                                                                                 AS feature_override
       ,GET_PATH($1,'feedback_contact_id:$oid')::string                                                                                             AS feedback_contact_id
       ,$1:foursquare_url::string                                                                                                                   AS foursquare_url
       ,$1:google_autopopulate_self_attempted::boolean                                                                                              AS google_autopopulate_self_attempted
       ,$1:googleplus_url::string                                                                                                                   AS googleplus_url
       ,$1:hide_welcome_email::boolean                                                                                                              AS hide_welcome_email
       ,$1:hours::variant                                                                                                                           AS hours
       ,$1:inactive::boolean                                                                                                                        AS inactive
       ,$1:instagram_screen_name::string                                                                                                            AS instagram_screen_name
       ,GET_PATH($1,'installed:$date')::datetime                                                                                                    AS installed_date
       ,$1:is_whitelabel::boolean                                                                                                                   AS is_whitelabel
       ,GET_PATH($1,'last_crm_req:$date')::datetime                                                                                                 AS last_crm_req
       ,GET_PATH($1,'last_probe_upload:$date')::datetime                                                                                            AS last_probe_upload
       ,$1:locale::string                                                                                                                           AS locale
       ,$1:logo_mime::string                                                                                                                        AS logo_mime
       ,$1:logo_original::string                                                                                                                    AS logo_original
       ,$1:logo_standard::string                                                                                                                    AS logo_standard
       ,$1:mist_api_secret::string                                                                                                                  AS mist_api_secret
       ,$1:name::string                                                                                                                             AS name
       ,$1:network_lead_submitted::boolean                                                                                                          AS network_lead_submitted
       ,$1:notifications_enabled::boolean                                                                                                           AS notifications_enabled
       ,$1:onboarded::boolean                                                                                                                       AS onboarded
       ,$1:opentable_id::string                                                                                                                     AS opentable_id
       ,$1:opentable_url::string                                                                                                                    AS opentable_url
       ,GET_PATH($1,'parent_id:$oid')::string                                                                                                       AS parent_id
       ,$1:phone::string                                                                                                                            AS phone
       ,$1:pilot_business::boolean                                                                                                                  AS pilot_business
       ,$1:pinterest_screen_name::string                                                                                                            AS pinterest_screen_name
       ,$1:privacy_policy::string                                                                                                                   AS privacy_policy
       ,$1:private_key::string                                                                                                                      AS private_key
       ,$1:private_ssid::string                                                                                                                     AS private_ssid
       ,$1:public_ssid::string                                                                                                                      AS public_ssid
       ,$1:ruckus_password::string                                                                                                                  AS ruckus_password
       ,$1:ruckus_venue_id::string                                                                                                                  AS ruckus_venue_id
       ,$1:ruckus_venue_psk::string                                                                                                                 AS ruckus_venue_psk
       ,$1:salesforce_id::string                                                                                                                    AS salesforce_id
       ,$1:shortname::string                                                                                                                        AS shortname
       ,$1:terms_of_service::string                                                                                                                 AS terms_of_service
       ,$1:test_business::boolean                                                                                                                   AS test_business
       ,CASE WHEN GET_PATH($1,'ticket_revenue_avg:$numberLong') is not null THEN null ELSE GET_PATH($1,'ticket_revenue_avg:$numberLong')::float END AS ticket_revenue_avg
       ,$1:time_zone::string                                                                                                                        AS time_zone
       ,$1:tripadvisor_url::string                                                                                                                  AS tripadvisor_url
       ,$1:twitter_screen_name::string                                                                                                              AS twitter_screen_name
       ,GET_PATH($1,'updated:$date')::datetime                                                                                                      AS updated
       ,$1:userdata_optional::boolean                                                                                                               AS userdata_optional
       ,$1:webform_trigger_enabled::boolean                                                                                                         AS webform_trigger_enabled
       ,$1:website_url::string                                                                                                                      AS website_url
       ,$1:yelp_url::string                                                                                                                         AS yelp_url
       ,$1:youtube_url::string                                                                                                                      AS youtube_url
       ,CURRENT_DATE()                                                                                                                              AS asof_date
FROM {{ most_recent_s3_file_name ('_STAGE','S3_MONGO_STAGE','.*/portal_businessprofile/.*/portal_businessprofile.json') }}