select $1:_id:"$oid"::string                       as trigger_id,
       $1:business_id:"$oid"::string              as business_id,
       $1:demographic_rule::string         as demographic_rule,
       $1:enabled::boolean                 as enabled,
       $1:event_driven::boolean            as event_driven,
       $1:free::boolean                    as free,
       $1:hidden::boolean                  as hidden,
       $1:is_custom::boolean               as is_custom,
       $1:is_recurring::boolean            as is_recurring,
       $1:linked::boolean                  as linked,
       $1:message_id:"$oid"::string               as message_id,
       parse_json($1:parameters)::variant as parameters,
       $1:parent_id:"$oid"::string                as parent_id,
       $1:purchase_rule::string            as purchase_rule,
       parse_json($1:rule)::variant        as rule,
       {{ parse_json_float('$1:timebox') }}                   as timebox,
       $1:title::string                    as title,
       current_date                        as asof_date
from {{ most_recent_s3_file_name( '_STAGE', 'S3_MONGO_STAGE', '.*/smbsite_trigger.json') }}
