SELECT $1:_id:"$oid"::STRING                                                                                         AS PORTAL_ROUTER_ID,
       $1:adding_client::STRING                                                                                      AS ADDING_CLIENT,
       $1:adding_device_id::STRING                                                                                   AS ADDING_DEVICE_ID,
       $1:business_id:"$oid"::STRING                                                                                 AS BUSINESS_ID,
       $1:created:"$date"::DATETIME                                                                                  AS CREATED,
       $1:current_routertype_id::STRING                                                                              AS CURRENT_ROUTERTYPE_ID,
       $1:current_version_id:"$oid"::STRING                                                                          AS CURRENT_VERSION_ID,
       $1:date_added:"$date"::DATETIME                                                                               AS DATE_ADDED,
       $1:desired_version_id:"$oid"::STRING                                                                          AS DESIRED_VERSION_ID,
       $1:dns_type::STRING                                                                                           AS DNS_TYPE,
       $1:downlink_speed::STRING                                                                                     AS DOWNLINK_SPEED,
       $1:gateway_id::STRING                                                                                         AS GATEWAY_ID,
       $1:installed:"$date"::DATETIME                                                                                AS INSTALLED,
       $1:internal_ipaddress::STRING                                                                                 AS INTERNAL_IPADDRESS,
       $1:ipaddress::STRING                                                                                          AS IPADDRESS,
       $1:key_1::STRING                                                                                              AS KEY_1,
       $1:key_2::STRING                                                                                              AS KEY_2,
       {{ string_to_MAC('$1:lan_mac') }}                                                                             AS LAN_MAC, --<--
       $1:last_crm_req:"$date"::DATETIME                                                                             AS LAST_CRM_REQ,
       $1:last_ping:"$date"::DATETIME                                                                                AS LAST_PING,
       $1:last_probe_upload:"$date"::DATETIME                                                                        AS LAST_PROBE_UPLOAD,
       $1:last_sys_load:"$date"::DATETIME                                                                            AS LAST_SYS_LOAD,
       $1:last_sys_memfree:"$date"::DATETIME                                                                         AS LAST_SYS_MEMFREE,
       $1:last_sys_uptime:"$date"::DATETIME                                                                          AS LAST_SYS_UPTIME,
       $1:last_update:"$date"::DATETIME                                                                              AS LAST_UPDATE,
       $1:last_update_check:"$date"::DATETIME                                                                        AS LAST_UPDATE_CHECK,
       CASE
           WHEN $1:last_wifidog_uptime:"$numberLong" IS NOT NULL THEN NULL
           ELSE $1:last_wifidog_uptime::INTEGER END                                                                  AS LAST_WIFIDOG_UPTIME,
       $1:latitude::FLOAT                                                                                            AS LATITUDE,
       $1:longitude::FLOAT                                                                                           AS LONGITUDE,
       $1:management_port::NUMBER(38, 0)                                                                             AS MANAGEMENT_PORT,
       $1:original_password::STRING                                                                                  AS ORIGINAL_PASSWORD,
       $1:original_username::STRING                                                                                  AS ORIGINAL_USERNAME,
       $1:password::STRING                                                                                          AS PASSWORD,
       $1:pinged_recently::BOOLEAN                                                                                   AS PINGED_RECENTLY,
       $1:security_1::STRING                                                                                         AS SECURITY_1,
       $1:security_2::STRING                                                                                         AS SECURITY_2,
       $1:security_3::STRING                                                                                         AS SECURITY_3,
       $1:security_4::STRING                                                                                         AS SECURITY_4,
       $1:ssh_portnum::NUMBER(38, 0)                                                                                 AS SSH_PORTNUM,
       $1:ssh_tunnel_available::BOOLEAN                                                                              AS SSH_TUNNEL_AVAILABLE,
       $1:ssid_1::STRING                                                                                             AS SSID_1,
       $1:ssid_2::STRING                                                                                             AS SSID_2,
       $1:ssid_3::STRING                                                                                             AS SSID_3,
       $1:ssid_4::STRING                                                                                             AS SSID_4,
       $1:stock_firmware_version_id::STRING                                                                          AS STOCK_FIRMWARE_VERSION_ID,
       $1:stock_routertype_id::STRING                                                                                AS STOCK_ROUTERTYPE_ID,
       $1:street_address::STRING                                                                                     AS STREET_ADDRESS,
       $1:time_zone::STRING                                                                                          AS TIME_ZONE,
       $1:update_available:"$date"::DATETIME                                                                         AS UPDATE_AVAILABLE,
       $1:updated:"$date"::DATETIME                                                                                  AS UPDATED,
       $1:uplink_speed::NUMBER(38, 0)                                                                                AS UPLINK_SPEED,
       $1:username::STRING                                                                                           AS USERNAME,
       $1:userprofile_id:"$oid"::STRING                                                                              AS USERPROFILE_ID,
       $1:wan_connection_type::STRING                                                                                AS WAN_CONNECTION_TYPE,
       $1:wan_dns::STRING                                                                                            AS WAN_DNS,
       $1:wan_gateway::STRING                                                                                        AS WAN_GATEWAY,
       $1:wan_ip::STRING                                                                                             AS WAN_IP,
       {{ string_to_MAC('$1:wan_mac') }}                                                                             AS WAN_MAC, --<--
       $1:wan_subnet_mask::STRING                                                                                    AS WAN_SUBNET_MASK,
       $1:wifidog_profile::STRING                                                                                    AS WIFIDOG_PROFILE,
       {{ string_to_MAC('$1:wlan_mac') }}                                                                            AS WLAN_MAC,
       current_date                                                                                          AS ASOF_DATE
FROM {{ most_recent_s3_file_name('_STAGE', 'S3_MONGO_STAGE', '.*/portal_router.json') }}
