SELECT $1:_id:"$oid"::STRING                     AS EMAILBLAST_ID,
       $1:business_id:"$oid"::STRING             AS BUSINESS_ID,
       $1:campaign_id:"$oid"::STRING             AS CAMPAIGN_ID,
       $1:bounced_filtered_count::INTEGER        AS BOUNCED_FILTERED_COUNT,
       $1:created:"$date"::DATETIME              AS CREATED,
       $1:invalid_filtered_count::INTEGER        AS INVALID_FILTERED_COUNT,
       $1:message_id:"$oid"::STRING              AS MESSAGE_ID,
       $1:queued:"$date"::DATETIME               AS QUEUED,
       $1:queued_count::INTEGER                  AS QUEUED_COUNT,
       $1:target_id:"$oid"::STRING               AS TARGET_ID,
       $1:target_size::STRING                    AS TARGET_SIZE,
       $1:scheduled:"$date"::DATETIME            AS SCHEDULED,
       $1:sending:"$date"::DATETIME              AS SENDING,
       $1:sent:"$date"::DATETIME                 AS SENT,
       $1:unsubscribed_filtered_count::INTEGER   AS UNSUBSCRIBED_FILTERED_COUNT,
       $1:unvisited_customers::INTEGER           AS UNVISITED_CUSTOMERS,
       $1:employee_filtered_count::INTEGER       AS EMPLOYEE_FILTERED_COUNT,
       $1:invalid_target_filtered_count::INTEGER AS INVALID_TARGET_FILTERED_COUNT,
       current_date                      AS ASOF_DATE
FROM {{ most_recent_s3_file_name('_STAGE', 'S3_MONGO_STAGE', '.*/smbsite_emailblast.json') }}
