create file format ZENSTAG.AMS_ROUTERS.S3_RDS_EXPORTER_CSV_FORMAT
FIELD_DELIMITER=','
ESCAPE_UNENCLOSED_FIELD='\\'
ESCAPE = '\\'
RECORD_DELIMITER='\n'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL=true
null_if=('NULL')
skip_header = 1;