-------------------------------------------------------------------
----------------- Business Profile Snowpipe
-------------------------------------------------------------------

create stage if not exists ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_S3_STAGE
    file_format = ( TYPE = JSON )
    url = 's3://zd-uw2-data-archives/mongo/portal_businessprofile/'
    credentials = ( aws_role = 'arn:aws:iam::504740723475:role/zd-uw2-mongo-snowflake-stage');

-- Table will hold raw mongo data from our snowpipe
create table if not exists ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_ARCHIVE (
    RAW_RECORD VARIANT, -- Store raw so pipe doesnt need to be torn down on schema update
    INSERT_ID NUMBER AUTOINCREMENT
);

-- Pipe will insert raw data from stage to our raw archive table
create pipe if not exists ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_SNOWPIPE auto_ingest=true as
COPY INTO ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_ARCHIVE(RAW_RECORD)
FROM @ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_S3_STAGE
on_error = 'continue';

-- Stream handles data access so that DML's do not consume the same records twice. Think of it like an offset.
-- Our task will read off this stream periodically only receiving new records.
-- Note a DML statement is required for the offest to progress. A simple select statment will have no effect to offset advancement
create stream if not exists ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_STREAM on table ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_ARCHIVE;

-- Task will run like a typical cron job. This task will read off the stream, transform the raw data and run an upsert against business_id.
create task if not exists ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_UPSERT_TASK
    WAREHOUSE = ZENSAND
    SCHEDULE = 'USING CRON * * * * * UTC'
WHEN
    SYSTEM$STREAM_HAS_DATA('ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_STREAM')
AS
    MERGE INTO ZENSAND.CRM.PORTAL_BUSINESSPROFILE as pbp USING (
        SELECT
            GET_PATH($1, '_id:$oid') as business_id,
            $1:address::variant as address,
            $1:announcements::string as announcements,
            $1:authorizations[0]::string as authorizations,
            $1:authorizations_optional::boolean as authorizations_optional,
            $1:contact_firstname::string as contact_firstname,
            $1:contact_lastname::string as contact_lastname,
            $1:contact_phone as contact_phone,
            GET_PATH($1, 'created:$date')::datetime as created_date,
            $1:customer_tags::variant as customer_tags,
            $1:facebook_access_token::string as facebook_access_token,
            $1:facebook_like_url::string as facebook_like_url,
            $1:feature_override::string as feature_override,
            GET_PATH($1,'feedback_contact_id:$oid')::string as feedback_contact_id,
            $1:foursquare_url::string as foursquare_url,
            $1:google_autopopulate_self_attempted::boolean as google_autopopulate_self_attempted,
            $1:googleplus_url::string as googleplus_url,
            $1:hide_welcome_email::boolean as hide_welcome_email,
            $1:hours::variant as hours,
            $1:inactive::boolean as inactive,
            $1:instagram_screen_name::string as instagram_screen_name,
            GET_PATH($1, 'installed:$date')::datetime as installed_date,
            $1:is_whitelabel::boolean as is_whitelabel,
            GET_PATH($1, 'last_crm_req:$date')::datetime as last_crm_req,
            GET_PATH($1, 'last_probe_upload:$date')::datetime as last_probe_upload,
            $1:locale::string as locale,
            $1:logo_mime::string as logo_mime,
            $1:logo_original::string as logo_original,
            $1:logo_standard::string as logo_standard,
            $1:mist_api_secret::string as mist_api_secret,
            $1:name::string as name,
            $1:network_lead_submitted::boolean as network_lead_submitted,
            $1:notifications_enabled::boolean as notifications_enabled,
            $1:onboarded::boolean as onboarded,
            $1:opentable_id::string as opentable_id,
            $1:opentable_url::string as opentable_url,
            GET_PATH($1, 'parent_id:$oid')::string as parent_id,
            $1:phone::string as phone,
            $1:pilot_business::boolean as pilot_business,
            $1:pinterest_screen_name::string as pinterest_screen_name,
            $1:privacy_policy::string as privacy_policy,
            $1:private_key::string as private_key,
            $1:private_ssid::string as private_ssid,
            $1:public_ssid::string as public_ssid,
            $1:ruckus_password::string as ruckus_password,
            $1:ruckus_venue_id::string as ruckus_venue_id,
            $1:ruckus_venue_psk::string as ruckus_venue_psk,
            $1:salesforce_id::string as salesforce_id,
            $1:shortname::string as shortname,
            $1:terms_of_service::string as terms_of_service,
            $1:test_business::boolean as test_business,
            case when GET_PATH($1, 'ticket_revenue_avg:$numberLong') is null then null
            else GET_PATH($1, 'ticket_revenue_avg:$numberLong')::float end as ticket_revenue_avg,
            $1:time_zone::string as time_zone,
            $1:tripadvisor_url::string as tripadvisor_url,
            $1:twitter_screen_name::string as twitter_screen_name,
            GET_PATH($1, 'updated:$date')::datetime as updated,
            $1:userdata_optional::boolean as userdata_optional,
            $1:webform_trigger_enabled::boolean as  webform_trigger_enabled,
            $1:website_url::string as website_url,
            $1:yelp_url::string as yelp_url,
            $1:youtube_url::string as youtube_url,
            CURRENT_DATE() as asof_date
        FROM ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_STREAM
    ) as pbp_stage ON pbp.business_id = pbp_stage.business_id
    WHEN MATCHED THEN
        UPDATE SET
            address = pbp_stage.address,
            announcements = pbp_stage.announcements,
            authorizations = pbp_stage.authorizations,
            authorizations_optional = pbp_stage.authorizations_optional,
            contact_firstname = pbp_stage.contact_firstname,
            contact_lastname = pbp_stage.contact_lastname,
            contact_phone = pbp_stage.contact_phone,
            created_date = pbp_stage.created_date,
            customer_tags = pbp_stage.customer_tags,
            facebook_access_token = pbp_stage.facebook_access_token,
            facebook_like_url = pbp_stage.facebook_like_url,
            feature_override = pbp_stage.feature_override,
            feedback_contact_id = pbp_stage.feedback_contact_id,
            foursquare_url = pbp_stage.foursquare_url,
            google_autopopulate_self_attempted = pbp_stage.google_autopopulate_self_attempted,
            googleplus_url = pbp_stage.googleplus_url,
            hide_welcome_email = pbp_stage.hide_welcome_email,
            hours = pbp_stage.hours,
            inactive = pbp_stage.inactive,
            instagram_screen_name = pbp_stage.instagram_screen_name,
            installed_date = pbp_stage.installed_date,
            is_whitelabel = pbp_stage.is_whitelabel,
            last_crm_req = pbp_stage.last_crm_req,
            last_probe_upload = pbp_stage.last_probe_upload,
            locale = pbp_stage.locale,
            logo_mime = pbp_stage.logo_mime,
            logo_original = pbp_stage.logo_original,
            logo_standard = pbp_stage.logo_standard,
            mist_api_secret = pbp_stage.mist_api_secret,
            name = pbp_stage.name,
            network_lead_submitted = pbp_stage.network_lead_submitted,
            notifications_enabled = pbp_stage.notifications_enabled,
            onboarded = pbp_stage.onboarded,
            opentable_id = pbp_stage.opentable_id,
            opentable_url = pbp_stage.opentable_url,
            parent_id = pbp_stage.parent_id,
            phone = pbp_stage.phone,
            pilot_business = pbp_stage.pilot_business,
            pinterest_screen_name = pbp_stage.pinterest_screen_name,
            privacy_policy = pbp_stage.privacy_policy,
            private_key = pbp_stage.private_key,
            private_ssid = pbp_stage.private_ssid,
            public_ssid = pbp_stage.public_ssid,
            ruckus_password = pbp_stage.ruckus_password,
            ruckus_venue_id = pbp_stage.ruckus_venue_id,
            ruckus_venue_psk = pbp_stage.ruckus_venue_psk,
            salesforce_id = pbp_stage.salesforce_id,
            shortname = pbp_stage.shortname,
            terms_of_service = pbp_stage.terms_of_service,
            test_business = pbp_stage.test_business,
            ticket_revenue_avg = pbp_stage.ticket_revenue_avg,
            time_zone = pbp_stage.time_zone,
            tripadvisor_url = pbp_stage.tripadvisor_url,
            twitter_screen_name = pbp_stage.twitter_screen_name,
            updated = pbp_stage.updated,
            userdata_optional = pbp_stage.userdata_optional,
            webform_trigger_enabled = pbp_stage.webform_trigger_enabled,
            website_url = pbp_stage.website_url,
            yelp_url = pbp_stage.yelp_url,
            youtube_url = pbp_stage.youtube_url,
            asof_date = pbp_stage.asof_date
    WHEN NOT MATCHED THEN -- When above ON statement does not find a match insert as new record
        INSERT (business_id,
            address,
            announcements,
            authorizations,
            authorizations_optional,
            contact_firstname,
            contact_lastname,
            contact_phone,
            created_date,
            customer_tags,
            facebook_access_token,
            facebook_like_url,
            feature_override,
            feedback_contact_id,
            foursquare_url,
            google_autopopulate_self_attempted,
            googleplus_url,
            hide_welcome_email,
            hours,
            inactive,
            instagram_screen_name,
            installed_date,
            is_whitelabel,
            last_crm_req,
            last_probe_upload,
            locale,
            logo_mime,
            logo_original,
            logo_standard,
            mist_api_secret,
            name,
            network_lead_submitted,
            notifications_enabled,
            onboarded,
            opentable_id,
            opentable_url,
            parent_id,
            phone,
            pilot_business,
            pinterest_screen_name,
            privacy_policy,
            private_key,
            private_ssid,
            public_ssid,
            ruckus_password,
            ruckus_venue_id,
            ruckus_venue_psk,
            salesforce_id,
            shortname,
            terms_of_service,
            test_business,
            ticket_revenue_avg,
            time_zone,
            tripadvisor_url,
            twitter_screen_name,
            updated,
            userdata_optional,
            webform_trigger_enabled,
            website_url,
            yelp_url,
            youtube_url,
            asof_date)
        VALUES (
        pbp_stage.business_id,
        pbp_stage.address,
        pbp_stage.announcements,
        pbp_stage.authorizations,
        pbp_stage.authorizations_optional,
        pbp_stage.contact_firstname,
        pbp_stage.contact_lastname,
        pbp_stage.contact_phone,
        pbp_stage.created_date,
        pbp_stage.customer_tags,
        pbp_stage.facebook_access_token,
        pbp_stage.facebook_like_url,
        pbp_stage.feature_override,
        pbp_stage.feedback_contact_id,
        pbp_stage.foursquare_url,
        pbp_stage.google_autopopulate_self_attempted,
        pbp_stage.googleplus_url,
        pbp_stage.hide_welcome_email,
        pbp_stage.hours,
        pbp_stage.inactive,
        pbp_stage.instagram_screen_name,
        pbp_stage.installed_date,
        pbp_stage.is_whitelabel,
        pbp_stage.last_crm_req,
        pbp_stage.last_probe_upload,
        pbp_stage.locale,
        pbp_stage.logo_mime,
        pbp_stage.logo_original,
        pbp_stage.logo_standard,
        pbp_stage.mist_api_secret,
        pbp_stage.name,
        pbp_stage.network_lead_submitted,
        pbp_stage.notifications_enabled,
        pbp_stage.onboarded,
        pbp_stage.opentable_id,
        pbp_stage.opentable_url,
        pbp_stage.parent_id,
        pbp_stage.phone,
        pbp_stage.pilot_business,
        pbp_stage.pinterest_screen_name,
        pbp_stage.privacy_policy,
        pbp_stage.private_key,
        pbp_stage.private_ssid,
        pbp_stage.public_ssid,
        pbp_stage.ruckus_password,
        pbp_stage.ruckus_venue_id,
        pbp_stage.ruckus_venue_psk,
        pbp_stage.salesforce_id,
        pbp_stage.shortname,
        pbp_stage.terms_of_service,
        pbp_stage.test_business,
        pbp_stage.ticket_revenue_avg,
        pbp_stage.time_zone,
        pbp_stage.tripadvisor_url,
        pbp_stage.twitter_screen_name,
        pbp_stage.updated,
        pbp_stage.userdata_optional,
        pbp_stage.webform_trigger_enabled,
        pbp_stage.website_url,
        pbp_stage.yelp_url,
        pbp_stage.youtube_url,
        pbp_stage.asof_date
        );

ALTER TASK ZENSAND.CRM.MONGO_PORTAL_BUSINESSPROFILE_UPSERT_TASK RESUME;
