{{ config(materialized='table') }}

SELECT 'test_cc1_bid_sighting_1'::VARCHAR(16777216) AS sighting_id,
    'WALKBY'::VARCHAR(16777216) AS classification,
    dateadd(hour, -36, current_timestamp())::TIMESTAMP_NTZ(9) AS start_time,
    dateadd(hour, -34, current_timestamp())::TIMESTAMP_NTZ(9) AS end_time,
    5::NUMBER(38,0) AS blip_count,
    -50::FLOAT AS max_rssi,
    -40::FLOAT AS min_rssi,
    -45::FLOAT AS avg_rssi,
    2000::NUMBER(38,6) AS dwell_time,
    array_construct(object_construct('client_mac_anonymization', 'test_cc1_client_mac_anon', 'vendor_prefix', 'test_cc1_cli'))::ARRAY AS anonymous_client_mac_info,
    array_construct(object_construct('client_mac', 'test_cc1_client_mac', 'client_mac_anonymization', 'test_cc1_client_mac_anon'))::ARRAY AS client_mac_info,
    'test_cc1_userprofile_id'::VARCHAR(16777216) AS contact_id,
    'test_cc1@test.com'::VARCHAR(16777216) AS contact_info,
    'EMAIL'::VARCHAR(16777216) AS contact_method,
    'test_cc1_bid'::VARCHAR(16777216) AS location_id,
    'test_cc1_bid'::VARCHAR(16777216) AS business_id,
    'TEST_CC1_BID'::VARCHAR(16777216) AS account_id,
    'test_cc1_parent_bid'::VARCHAR(16777216) AS parent_id,
    'TRUE'::BOOLEAN AS known_to_zenreach,
    'TRUE'::BOOLEAN AS known_to_merchant_account,
    'TRUE'::BOOLEAN AS known_to_merchant_location,
    'captive_1'::VARCHAR(16777216) AS privacy_version,
    'captive_1'::VARCHAR(16777216) AS terms_version,
    'captive_1'::VARCHAR(16777216) AS bundle_version,
    'FALSE'::BOOLEAN AS is_employee
UNION ALL SELECT 'test_cc2_bid_sighting_1'::VARCHAR(16777216) AS sighting_id,
    'WALKIN'::VARCHAR(16777216) AS classification,
    dateadd(hour, -36, current_timestamp())::TIMESTAMP_NTZ(9) AS start_time,
    dateadd(hour, -35, current_timestamp())::TIMESTAMP_NTZ(9) AS end_time,
    5::NUMBER(38,0) AS blip_count,
    -50::FLOAT AS max_rssi,
    -40::FLOAT AS min_rssi,
    -45::FLOAT AS avg_rssi,
    2000::NUMBER(38,6) AS dwell_time,
    array_construct(object_construct('client_mac_anonymization', 'test_cc2_client_mac_anon', 'vendor_prefix', 'test_cc2_cli'))::ARRAY AS anonymous_client_mac_info,
    array_construct(object_construct('client_mac', 'test_cc2_client_mac', 'client_mac_anonymization', 'test_cc2_client_mac_anon'))::ARRAY AS client_mac_info,
    'test_cc2_userprofile_id'::VARCHAR(16777216) AS contact_id,
    'test_cc2@test.com'::VARCHAR(16777216) AS contact_info,
    'EMAIL'::VARCHAR(16777216) AS contact_method,
    'test_cc2_bid'::VARCHAR(16777216) AS location_id,
    'test_cc2_bid'::VARCHAR(16777216) AS business_id,
    'TEST_CC2_BID'::VARCHAR(16777216) AS account_id,
    'test_cc2_parent_bid'::VARCHAR(16777216) AS parent_id,
    'TRUE'::BOOLEAN AS known_to_zenreach,
    'TRUE'::BOOLEAN AS known_to_merchant_account,
    'TRUE'::BOOLEAN AS known_to_merchant_location,
    'captive_1'::VARCHAR(16777216) AS privacy_version,
    'captive_1'::VARCHAR(16777216) AS terms_version,
    'captive_1'::VARCHAR(16777216) AS bundle_version,
    'FALSE'::BOOLEAN AS is_employee
UNION ALL SELECT 'test_cc3_bid_sighting_1'::VARCHAR(16777216) AS sighting_id,
    'WALKIN'::VARCHAR(16777216) AS classification,
    dateadd(hour, -36, current_timestamp())::TIMESTAMP_NTZ(9) AS start_time,
    dateadd(hour, -34, current_timestamp())::TIMESTAMP_NTZ(9) AS end_time,
    5::NUMBER(38,0) AS blip_count,
    -50::FLOAT AS max_rssi,
    -40::FLOAT AS min_rssi,
    -45::FLOAT AS avg_rssi,
    2000::NUMBER(38,6) AS dwell_time,
    array_construct(object_construct('client_mac_anonymization', 'test_cc3_client_mac_anon', 'vendor_prefix', 'test_cc3_cli'))::ARRAY AS anonymous_client_mac_info,
    array_construct(object_construct('client_mac', 'test_cc3_client_mac', 'client_mac_anonymization', 'test_cc3_client_mac_anon'))::ARRAY AS client_mac_info,
    'test_cc3_userprofile_id'::VARCHAR(16777216) AS contact_id,
    'test_cc3@test.com'::VARCHAR(16777216) AS contact_info,
    'EMAIL'::VARCHAR(16777216) AS contact_method,
    'test_cc3_bid'::VARCHAR(16777216) AS location_id,
    'test_cc3_bid'::VARCHAR(16777216) AS business_id,
    'TEST_CC3_BID'::VARCHAR(16777216) AS account_id,
    'test_cc3_parent_bid'::VARCHAR(16777216) AS parent_id,
    'TRUE'::BOOLEAN AS known_to_zenreach,
    'TRUE'::BOOLEAN AS known_to_merchant_account,
    'TRUE'::BOOLEAN AS known_to_merchant_location,
    'captive_1'::VARCHAR(16777216) AS privacy_version,
    'captive_1'::VARCHAR(16777216) AS terms_version,
    'captive_1'::VARCHAR(16777216) AS bundle_version,
    'FALSE'::BOOLEAN AS is_employee


