-----------------------------------------------------------------------
---------------------  smbsite_messagelog -----------------------------
-----------------------------------------------------------------------

use database &{dbname};
use warehouse &{whname};
use schema &{stageschema}; -- run in _stage but insert into CRM
use role &{rolename};

alter session set QUOTED_IDENTIFIERS_IGNORE_CASE = false;

MERGE INTO &{dbname}.&{schemaname}.SMBSITE_MESSAGELOG
as target USING
(
    select
    $1:id::string as messagelog_id,
    $1:email_blast_id::string as email_blast_id,
    $1:blast_id::string as blast_id, 
    $1:offer_log_id::string as offer_log_id,
    $1:schedule_id::string as schedule_id,
    $1:blacklisted::boolean as blacklisted,
    $1:bounced::timestamp as bounced,
    $1:bounced_reason::string as bounced_reason,
    $1:bounced_response_code::string as bounced_response_code,
    $1:bounced_response_reason::string as bounced_response_reason,
    $1:bounced_response_detail::string as bounced_response_detail, 
    $1:business_id::string as business_id,
    $1:source_business_id:: string as source_business_id,
    $1:visited_business_id::string as visited_business_id, 
    $1:visited::timestamp as visited, 
    $1:celery_dequeued::timestamp as celery_dequeued,
    $1:celery_queue_duration::float as celery_queue_duration,
    $1:clicked::timestamp as clicked,
    $1:client_name::string as client_name,
    $1:client_os::string as client_os,
    $1:client_type::string as client_type,
    $1:confirmation::string as confirmation,
    $1:customer_loyalty_type::string as customer_loyalty_type,
    $1:delivered::timestamp as delivered,
    $1:device_type::string as device_type,
    $1:domain::string as domain,
    $1:invalid::boolean as invalid,
    $1:last_seen::timestamp as last_seen,
    $1:message_id::string as message_id,
    $1:non_customer::boolean as non_customer,
    $1:opened::timestamp as opened,
    $1:parent_trigger_id::string as parent_trigger_id,
    $1:pool::string as pool,
    $1:purchase_count::integer as purchase_count,
    $1:recipient_domain::string as recipient_domain,
    $1:sent::timestamp as sent,
    $1:success::boolean as success,
    $1:test_mode::boolean as test_mode,
    $1:test_user::boolean as test_user,
    $1:trackable::boolean as trackable,
    $1:trigger_id::string as trigger_id,
    $1:unsubscribed::timestamp as unsubscribed,
    $1:unsubscribed_reason::string as unsubscribed_reason,
    $1:user_agent::string as user_agent,
    $1:userprofile_id::string as userprofile_id,
    $1:visit_count::integer as visit_count,
    $1:whitelisted::boolean as whitelisted,
    $1:source::string as source, 
    $1:scheduler::string as scheduler, 
    $1:return_time::integer as return_time, 
    $1:updated::timestamp as updated,
    nvl($1:sightingid,'')::string as sighting_id,
    to_date('&{asof_date}') as asof_date
FROM @&{stagename}/&{stagepath}/smbsite_messagelog00000.json (file_format => 's3_mongo_json_format')
) as source 
ON target.messagelog_id = source.messagelog_id
WHEN matched THEN update 
SET 
    target.EMAIL_BLAST_ID=source.EMAIL_BLAST_ID,
    target.BLAST_ID=source.BLAST_ID,
    target.OFFER_LOG_ID=source.OFFER_LOG_ID,
    target.SCHEDULE_ID=source.SCHEDULE_ID,
    target.BLACKLISTED=source.BLACKLISTED,
    target.BOUNCED=source.BOUNCED,
    target.BOUNCED_REASON=source.BOUNCED_REASON,
    target.BOUNCED_RESPONSE_CODE=source.BOUNCED_RESPONSE_CODE,
    target.BOUNCED_RESPONSE_REASON=source.BOUNCED_RESPONSE_REASON,
    target.BOUNCED_RESPONSE_DETAIL=source.BOUNCED_RESPONSE_DETAIL,
    target.BUSINESS_ID=source.BUSINESS_ID,
    target.SOURCE_BUSINESS_ID=source.SOURCE_BUSINESS_ID,
    target.VISITED_BUSINESS_ID=source.VISITED_BUSINESS_ID,
    target.VISITED=source.VISITED,
    target.CELERY_DEQUEUED=source.CELERY_DEQUEUED,
    target.CELERY_QUEUE_DURATION=source.CELERY_QUEUE_DURATION,
    target.CLICKED=source.CLICKED,
    target.CLIENT_NAME=source.CLIENT_NAME,
    target.CLIENT_OS=source.CLIENT_OS,
    target.CLIENT_TYPE=source.CLIENT_TYPE,
    target.CONFIRMATION=source.CONFIRMATION,
    target.CUSTOMER_LOYALTY_TYPE=source.CUSTOMER_LOYALTY_TYPE,
    target.DELIVERED=source.DELIVERED,
    target.DEVICE_TYPE=source.DEVICE_TYPE,
    target.DOMAIN=source.DOMAIN,
    target.INVALID=source.INVALID,
    target.LAST_SEEN=source.LAST_SEEN,
    target.MESSAGE_ID=source.MESSAGE_ID,
    target.NON_CUSTOMER=source.NON_CUSTOMER,
    target.OPENED=source.OPENED,
    target.PARENT_TRIGGER_ID=source.PARENT_TRIGGER_ID,
    target.POOL=source.POOL,
    target.PURCHASE_COUNT=source.PURCHASE_COUNT,
    target.RECIPIENT_DOMAIN=source.RECIPIENT_DOMAIN,
    target.SENT=source.SENT,
    target.SUCCESS=source.SUCCESS,
    target.TEST_MODE=source.TEST_MODE,
    target.TEST_USER=source.TEST_USER,
    target.TRACKABLE=source.TRACKABLE,
    target.TRIGGER_ID=source.TRIGGER_ID,
    target.UNSUBSCRIBED=source.UNSUBSCRIBED,
    target.UNSUBSCRIBED_REASON=source.UNSUBSCRIBED_REASON,
    target.USER_AGENT=source.USER_AGENT,
    target.USERPROFILE_ID=source.USERPROFILE_ID,
    target.VISIT_COUNT=source.VISIT_COUNT,
    target.WHITELISTED=source.WHITELISTED,
    target.SOURCE=source.SOURCE,
    target.SCHEDULER=source.SCHEDULER,
    target.RETURN_TIME=source.RETURN_TIME,
    target.UPDATED=source.UPDATED,
    target.sighting_id=source.sighting_id,
    target.ASOF_DATE=source.ASOF_DATE
WHEN not matched then 
INSERT
( messagelog_id,
  email_blast_id,
  blast_id,
  blacklisted,
  bounced,
  bounced_reason,
  bounced_response_code,
  bounced_response_reason,
  bounced_response_detail,
  business_id,
  visited_business_id,
  visited,
  celery_dequeued,
  celery_queue_duration,
  clicked,
  client_name,
  client_os,
  client_type,
  confirmation,
  customer_loyalty_type,
  delivered,
  device_type,
  domain,
  invalid,
  last_seen,
  message_id,
  non_customer,
  opened,
  parent_trigger_id,
  pool,
  purchase_count,
  recipient_domain,
  sent,
  success,
  test_mode,
  test_user,
  trackable,
  trigger_id,
  unsubscribed,
  unsubscribed_reason,
  user_agent,
  userprofile_id,
  visit_count,
  whitelisted,
  source,
  scheduler,
  return_time,
  updated,
  sighting_id,
  asof_date)
VALUES (source.messagelog_id,
  source.email_blast_id,
  source.blast_id,
  source.blacklisted,
  source.bounced,
  source.bounced_reason,
  source.bounced_response_code,
  source.bounced_response_reason,
  source.bounced_response_detail,
  source.business_id,
  source.visited_business_id,
  source.visited,
  source.celery_dequeued,
  source.celery_queue_duration,
  source.clicked,
  source.client_name,
  source.client_os,
  source.client_type,
  source.confirmation,
  source.customer_loyalty_type,
  source.delivered,
  source.device_type,
  source.domain,
  source.invalid,
  source.last_seen,
  source.message_id,
  source.non_customer,
  source.opened,
  source.parent_trigger_id,
  source.pool,
  source.purchase_count,
  source.recipient_domain,
  source.sent,
  source.success,
  source.test_mode,
  source.test_user,
  source.trackable,
  source.trigger_id,
  source.unsubscribed,
  source.unsubscribed_reason,
  source.user_agent,
  source.userprofile_id,
  source.visit_count,
  source.whitelisted,
  source.source,
  source.scheduler,
  source.return_time,
  source.updated, 
  source.sighting_id,
  source.ASOF_DATE)
;






