WITH MERGED_SIGHTINGS_ AS (
    SELECT lower(LOCATION_ID) AS LOCATION_ID, CONTACT_INFO AS EMAIL, START_TIME, END_TIME
    FROM {{ ref('stg_presence__wifi_consented_sightings') }}
    WHERE CLASSIFICATION = 'Classification_WALKIN'
      AND CONTACT_METHOD = 'CONTACT_METHOD_EMAIL'
      AND IS_EMPLOYEE = 'FALSE'
      AND CONTACT_INFO IS NOT NULL
      AND END_TIME
        > TO_TIMESTAMP(1571097600000 / 1000)

    UNION ALL

    SELECT lower(BUSINESS_ID)              AS LOCATION_ID,
           CONTACT_INFO                    AS EMAIL,
           TO_TIMESTAMP(START_TIME / 1000) AS START_TIME,
           TO_TIMESTAMP(END_TIME / 1000)   AS END_TIME
    FROM {{ ref('stg_presence__enriched_sightings') }}
    WHERE STATUS = 'FINISHED'
      AND CONTACT_METHOD = 'EMAIL'
      AND CONTACT_INFO IS NOT NULL
      AND IS_WALK_IN = 'TRUE'
      AND END_TIME <= 1571097600000
)
SELECT LOCATION_ID, EMAIL, count(*) AS VISIT_COUNT, MIN(START_TIME) AS FIRST_SEEN, max(END_TIME) AS LAST_SEEN
FROM MERGED_SIGHTINGS_
GROUP BY (LOCATION_ID, EMAIL)