SELECT ID                         AS ACCOUNT_ID,
       RA.BILLING_INFO:id::STRING AS BILLING_INFO_ID,
       BILL_TO,
       CC_EMAILS,
       CODE                       AS ACCOUNT_CODE,
       COMPANY,
       CREATED_AT,
       DELETED_AT,
       EMAIL,
       FIRST_NAME,
       HOSTED_LOGIN_TOKEN,
       LAST_NAME,
       OBJECT,
       PREFERRED_LOCALE,
       STATE,
       TAX_EXEMPT,
       UPDATED_AT,
       USERNAME,
       VAT_NUMBER,
       ADDRESS,
       BILLING_INFO,
       SHIPPING_ADDRESSES,
       CUSTOM_FIELDS
FROM {{ source('RECURLY', 'ACCOUNTS') }} ra

