SELECT A.ACCOUNT:code::STRING                            AS ACCOUNT_CODE,
       A.ACCOUNT:company::STRING                         AS COMPANY,
       A.ACCOUNT: EMAIL::STRING                          AS EMAIL,
       A.ACCOUNT: FIRST_NAME::STRING                     AS FIRST_NAME,
       A.ACCOUNT: LAST_NAME::STRING                      AS LAST_NAME,
       A.ACCOUNT:parent_account_id::STRING               AS PARENT_ACCOUNT_ID,
       A.ACCOUNTING_CODE,
       A.CREATED_AT,
       A.CURRENCY,
       A.DESCRIPTION,
       A.END_DATE,
       A.ID,
       A.INVOICE_ID,
       A.INVOICE_NUMBER,
       A.LEGACY_CATEGORY,
       A.OBJECT,
       A.ORIGIN,
       A.ORIGINAL_LINE_ITEM_INVOICE_ID,
       A.PLAN_CODE,
       A.PREVIOUS_LINE_ITEM_ID,
       A.PRODUCT_CODE,
       A.QUANTITY,
       A.REFUND,
       A.START_DATE,
       A.STATE,
       A.SUBSCRIPTION_ID,
       A.TAXABLE,
       A.TAX_EXEMPT,
       A.TYPE,
       NVL(A.TAX, A.TAX__DE)                             AS TAX,
       NVL(A.UNIT_AMOUNT, A.UNIT_AMOUNT__DE)             AS UNIT_AMOUNT,
       NVL(A.PRORATION_RATE, A.PRORATION_RATE__DE)       AS PRORATION_RATE,
       NVL(A.DISCOUNT, A.DISCOUNT__DE)                   AS DISCOUNT,
       NVL(A.CREDIT_APPLIED, A.CREDIT_APPLIED__DE)       AS CREDIT_APPLIED,
       NVL(A.SUBTOTAL, A.SUBTOTAL__DE)                   AS SUBTOTAL,
       NVL(A.REFUNDED_QUANTITY, A.REFUNDED_QUANTITY__IT) AS REFUNDED_QUANTITY,
       A.UPDATED_AT,
       A.UUID
FROM {{ source('RECURLY', 'ADJUSTMENTS') }} A

