SELECT parse_json(S.$1):code::STRING                               AS ACCOUNT_CODE,
       parse_json(S.$1):id::STRING                                 AS ACCOUNT_ID,
       ID                                                          AS SUBSCRIPTION_ID,
       parse_json(S.$1):code::STRING                               AS PLAN_CODE,
       parse_json(S.$1):id::STRING                                 AS PLAN_ID,
       ACTIVATED_AT,
       AUTO_RENEW,
       BANK_ACCOUNT_AUTHORIZED_AT,
       CANCELED_AT,
       COLLECTION_METHOD,
       CREATED_AT,
       CURRENCY,
       CURRENT_PERIOD_ENDS_AT,
       CURRENT_PERIOD_STARTED_AT,
       CURRENT_TERM_ENDS_AT,
       CUSTOMER_NOTES,
       EXPIRATION_REASON,
       EXPIRES_AT,
       OBJECT,
       PO_NUMBER,
       STATE,
       TERMS_AND_CONDITIONS,
       TRIAL_ENDS_AT,
       TRIAL_STARTED_AT,
       UPDATED_AT,
       UUID                                                        AS RECURLY_SUBSCRIPTION_ID,
       NVL(NET_TERMS, NET_TERMS__IT)                               AS NET_TERMS,
       NVL(UNIT_AMOUNT, UNIT_AMOUNT__DE)                           AS UNIT_AMOUNT,
       NVL(ADD_ONS_TOTAL, ADD_ONS_TOTAL__DE)                       AS ADD_ONS_TOTAL,
       NVL(QUANTITY, QUANTITY__IT)                                 AS QUANTITY,
       NVL(SUBTOTAL, SUBTOTAL__DE)                                 AS SUBTOTAL,
       NVL(RENEWAL_BILLING_CYCLES, RENEWAL_BILLING_CYCLES__IT)     AS RENEWAL_BILLING_CYCLES,
       NVL(REMAINING_BILLING_CYCLES, REMAINING_BILLING_CYCLES__IT) AS REMAINING_BILLING_CYCLES,
       NVL(TOTAL_BILLING_CYCLES, TOTAL_BILLING_CYCLES__IT)         AS TOTAL_BILLING_CYCLES,
       CURRENT_TERM_STARTED_AT,
       CUSTOM_FIELDS,
       ADD_ONS,
       COUPON_REDEMPTIONS,
       PENDING_CHANGE
FROM {{ source('RECURLY', 'SUBSCRIPTIONS') }} S