WITH INVOICES AS (SELECT ACCOUNT,
                         ADDRESS,
                         BALANCE,
                         CLOSED_AT,
                         COLLECTION_METHOD,
                         CREATED_AT,
                         CREDIT_PAYMENTS,
                         CURRENCY,
                         CUSTOMER_NOTES,
                         DISCOUNT,
                         DUE_AT,
                         ID,
                         LINE_ITEMS,
                         NET_TERMS,
                         NUMBER,
                         OBJECT,
                         ORIGIN,
                         PAID,
                         PO_NUMBER,
                         PREVIOUS_INVOICE_ID,
                         STATE,
                         parse_json((CASE
                                         WHEN parse_json(SUBSCRIPTION_IDS)[0]::STRING IS NULL THEN '["One Off"]'
                                         ELSE SUBSCRIPTION_IDS END))::VARIANT AS SUBSCRIPTION_IDS,
                         SUBTOTAL,
                         TAX,
                         TERMS_AND_CONDITIONS,
                         TOTAL,
                         TRANSACTIONS,
                         TYPE,
                         UPDATED_AT,
                         VAT_NUMBER,
                         REFUNDABLE_AMOUNT,
                         TAX__DE,
                         DISCOUNT__DE,
                         REFUNDABLE_AMOUNT__DE,
                         BALANCE__DE,
                         PAID__DE,
                         TOTAL__DE,
                         SUBTOTAL__DE
                  FROM {{ source('RECURLY', 'INVOICES') }})
SELECT parse_json(I.$1):code::STRING                 AS ACCOUNT_CODE,
       parse_json(I.$1):id::STRING                   AS ACCOUNT_ID,
       parse_json(I.$1):company::STRING              AS COMPANY_NAME,
       CLOSED_AT,
       COLLECTION_METHOD,
       CREATED_AT,
       CURRENCY,
       CUSTOMER_NOTES,
       DUE_AT,
       ID                                            AS INVOICE_ID,
       LINE_ITEMS,
       NET_TERMS,
       NUMBER                                        AS INVOICE_NUMBER,
       OBJECT,
       ORIGIN,
       PO_NUMBER,
       PREVIOUS_INVOICE_ID,
       STATE,
       TERMS_AND_CONDITIONS,
       TYPE,
       UPDATED_AT,
       VAT_NUMBER,
       NVL(REFUNDABLE_AMOUNT, REFUNDABLE_AMOUNT__DE) AS REFUNDABLE_AMOUNT,
       NVL(TAX, TAX__DE)                             AS TAX,
       NVL(DISCOUNT, DISCOUNT__DE)                   AS DISCOUNT,
       NVL(BALANCE, BALANCE__DE)                     AS BALANCE,
       NVL(PAID, PAID__DE)                           AS PAID,
       NVL(TOTAL, TOTAL__DE)                         AS TOTAL,
       NVL(SUBTOTAL, SUBTOTAL__DE)                   AS SUBTOTAL,
       CREDIT_PAYMENTS[0]:original_invoice           AS ADJUSTMENT_INVOICE,
       CREDIT_PAYMENTS[0]:amount::NUMBER             AS ADJUSTMENT_AMOUNT,
       CREDIT_PAYMENTS[0]: OBJECT::STRING            AS ADJUSTMENT_TYPE,
       TRANSACTIONS[0]:uuid::STRING                  AS TRANSACTION_UUID,
       SUBS.VALUE::STRING                            AS SUBSCRIPTION_ID
FROM INVOICES I,
     LATERAL flatten(INPUT => SUBSCRIPTION_IDS) SUBS
