SELECT CR.ACCOUNT:code::STRING             AS ACCOUNT_CODE,
       CR.ACCOUNT:id::STRING               AS ACCOUNT_ID,
       CR.COUPON:code::STRING              AS COUPON_CODE,
       CR.COUPON:coupon_type::STRING       AS COUPON_TYPE,
       CR.COUPON:created_at::TIMESTAMP_NTZ AS COUPON_CREATED_AT,
       CR.COUPON:expired_at::TIMESTAMP_NTZ AS COUPON_EXPIRED_AT,
       CR.COUPON:discount: TYPE::STRING    AS DISCOUNT_TYPE,
       CR.COUPON:discount: PERCENT::NUMBER AS DISCOUNT,
       CR.COUPON:duration::STRING          AS DURATION,
       CR.COUPON:id::STRING                AS COUPON_ID,
       CREATED_AT,
       CURRENCY,
       DISCOUNTED,
       ID                                  AS COUPON_REDEMPTION_ID,
       OBJECT,
       STATE,
       UPDATED_AT,
       REMOVED_AT
FROM {{ source('RECURLY', 'COUPON_REDEMPTIONS') }} CR