SELECT $1                  AS INSIGHT_ID,
       $2                  AS AD_ACCOUNT_ID,
       $3                  AS CAMPAIGN_ID,
       $4                  AS AD_SET_ID,
       $5                  AS AD_ID,
       $6                  AS INSIGHT_TYPE,
       $7                  AS BREAKDOWN_TYPE,
       $8                  AS BREAKDOWN_VALUE,
       $9::INTEGER         AS IMPRESSIONS,
       $10::INTEGER        AS CLICKS,
       $11::INTEGER        AS WALKTHROUGHS,
       $12                 AS ENGAGEMENT,
       $13::INTEGER        AS SPEND_CENTS,
       $14::INTEGER        AS THRU_PLAYS,
       $15::INTEGER        AS VIDEO_PLAYS_AT_25_PERC,
       $16::INTEGER        AS VIDEO_PLAYS_AT_50_PERC,
       $17::INTEGER        AS VIDEO_PLAYS_AT_75_PERC,
       $18::INTEGER        AS VIDEO_PLAYS_AT_95_PERC,
       $19::INTEGER        AS VIDEO_PLAYS_AT_100_PERC,
       $20::INTEGER        AS VIDEO_PLAYS,
       $21::INTEGER        AS VIDEO_AVERAGE_PLAY_TIME,
       $22::INTEGER        AS INSTANT_EXPERIENCE_VIEW_TIME,
       $23::INTEGER        AS INSTANT_EXPERIENCE_VIEW_PERC,
       $24::INTEGER        AS LINK_CLICKS,
       $25::INTEGER        AS OUTBOUND_CLICKS,
       $26::INTEGER        AS INSTANT_EXPERIENCE_CLICKS_TO_OPEN,
       $27::INTEGER        AS INSTANT_EXPERIENCE_CLICKS_TO_START,
       $28::INTEGER        AS INSTANT_EXPERIENCE_OUTBOUND_CLICKS,
       $29::INTEGER        AS E_CPM_CENTS,
       $30::TIMESTAMP      AS LAST_SYNCED,
       $31::INTEGER        AS WALKTHROUGHS1_DAY,
       $32::INTEGER        AS WALKTHROUGHS7_DAY,
       $33::INTEGER        AS WALKTHROUGHS28_DAY,
       current_timestamp() AS ASOF_DATE
FROM {{ most_recent_s3_file_name ( 'ADS' , 'ARCHIVER_ADS_S3_STAGE' , '.*/nwfbcampaignsync/.*/insights_ads_v3.csv' ) }}

